Universe              = vanilla
executable            = runMVADataMaker.sh
arguments             = $(ProcId) 1 2 
GetEnv                = True
requirements          = (OpSysAndVer =?= "CentOS7")
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
+JobFlavour           = "workday"
# RequestCpus           = 8

#BsToMuMuGamma
queue 443

#BsToJpsi Gamma
#queue 254 
